let characters = [
  {
    characterName: "Peashooter",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Peashooter.png",
    plantType: "Pea Shooter",
    sunCost: "100",
    world: "None",
    damageType: "Single Target",
    specialAbility: "None",
  },
  {
    characterName: "Snow Pea",
    characterType: "Plant",
    gameVersions: ["PvZ"],
    Link: "images/SnowPea.png",
    plantType: "Pea Shooter",
    sunCost: "175",
    world: "None",
    damageType: "Freezing",
    specialAbility: "Slows enemies",
  },
  {
    characterName: "Sunflower",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Sunflower.png",
    plantType: "Sun Producer",
    sunCost: "50",
    world: "None",
    damageType: "None",
    specialAbility: "Produces Sun",
  },
  {
    characterName: "Wall-nut",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Wall-nut.png",
    plantType: "Defensive",
    sunCost: "50",
    world: "None",
    damageType: "None",
    specialAbility: "Blocks enemies",
  },
  {
    characterName: "Cherry Bomb",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/CherryBomb.png",
    plantType: "Explosive",
    sunCost: "150",
    world: "None",
    damageType: "Area Damage",
    specialAbility: "Instant Explosion",
  },
  {
    characterName: "Pea Pod",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/PeaPod.png",
    plantType: "Pea Shooter",
    sunCost: "125",
    world: "None",
    damageType: "Multi-target",
    specialAbility: "Shoots up to 5 peas",
  },
  {
    characterName: "Torchwood",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Torchwood.png",
    plantType: "Support",
    sunCost: "175",
    world: "None",
    damageType: "Enhancement",
    specialAbility: "Ignites peas for extra damage",
  },
  {
    characterName: "Grave Buster",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/GraveBuster.png",
    plantType: "Utility",
    sunCost: "0",
    world: "None",
    damageType: "None",
    specialAbility: "Removes graves",
  },
  {
    characterName: "Steel-Magnolia",
    characterType: "Plant",
    gameVersions: ["PvZ Heros"],
    Link: "images/Steel-Magnolia.png",
    plantType: "Support",
    sunCost: "125",
    world: "None",
    damageType: "None",
    specialAbility: "Shields plants",
  },
  {
    characterName: "Cabbage-pult",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Cabbage-pult.png",
    plantType: "Catapult",
    sunCost: "100",
    world: "Ancient Egypt",
    damageType: "Single Target",
    specialAbility: "Lobs cabbages over obstacles",
  },
  {
    characterName: "Kernel-pult",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Kernel-pult.png",
    plantType: "Catapult",
    sunCost: "100",
    world: "None",
    damageType: "Slowing and Damage",
    specialAbility: "Lobs kernels and butter",
  },
  {
    characterName: "Tangle Kelp",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/TangleKelp.png",
    plantType: "Aquatic",
    sunCost: "25",
    world: "Big Wave Beach",
    damageType: "Instant Kill",
    specialAbility: "Drags enemies underwater",
  },
  {
    characterName: "Snapdragon",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Snapdragon.png",
    plantType: "Area Damage",
    sunCost: "150",
    world: "Pirate Seas",
    damageType: "Fire",
    specialAbility: "Deals damage in 3 lanes",
  },
  {
    characterName: "Jalapeno",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Jalapeno.png",
    plantType: "Explosive",
    sunCost: "125",
    world: "None",
    damageType: "Lane Clear",
    specialAbility: "Burns an entire lane",
  },
  {
    characterName: "Mistletoe",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/Mistletoe.png",
    plantType: "Sniper",
    sunCost: "200",
    world: "Frostbite Caves",
    damageType: "Single Target",
    specialAbility: "Targets strongest zombies",
  },
  {
    characterName: "Pineapple",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/Pineapple.png",
    plantType: "Explosive",
    sunCost: "150",
    world: "Lost City",
    damageType: "Area Damage",
    specialAbility: "Destroys metal barriers",
  },
  {
    characterName: "Chili Bean",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/ChilliBean.png",
    plantType: "Explosive",
    sunCost: "50",
    world: "None",
    damageType: "Instant Kill",
    specialAbility: "Explodes and stuns nearby zombies",
  },
  {
    characterName: "Aloe",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/Aloe.png",
    plantType: "Support",
    sunCost: "75",
    world: "Jurassic Marsh",
    damageType: "None",
    specialAbility: "Heals plants",
  },
  {
    characterName: "Bonk Choy",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Link: "images/BonkChoy.png",
    plantType: "Melee",
    sunCost: "150",
    world: "Ancient Egypt",
    damageType: "High Melee",
    specialAbility: "Fast punches",
  },
  {
    characterName: "Lily Pad",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/LilyPad.png",
    plantType: "Utility",
    sunCost: "25",
    world: "None",
    damageType: "None",
    specialAbility: "Allows planting on water",
  },
  {
    characterName: "Squash",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Squash.png",
    plantType: "Instant Kill",
    sunCost: "50",
    world: "None",
    damageType: "Single Target",
    specialAbility: "Crushes one enemy",
  },
  {
    characterName: "Hypno-shroom",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Hypno-shroom.png",
    plantType: "Fungal",
    sunCost: "75",
    world: "Dark Ages",
    damageType: "None",
    specialAbility: "Turns zombies into allies",
  },
  {
    characterName: "Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Zombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Melee",
    specialAbility: "None",
  },
  {
    characterName: "Conehead Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/ConeheadZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Melee",
    specialAbility: "Additional armor",
  },
  {
    characterName: "Football Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/FootballZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Melee",
    specialAbility: "High speed and durability",
  },
  {
    characterName: "Digger Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/DiggerZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "None",
    specialAbility: "Bypasses plants",
  },
  {
    characterName: "Zomboni",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Zombini.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Area",
    specialAbility: "Crushes plants and leaves ice",
  },
  {
    characterName: "Buckethead Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/BucketheadZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Melee",
    specialAbility: "High durability",
  },
  {
    characterName: "Disco Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/DiscoZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Melee",
    specialAbility: "Summons backup dancers",
  },
  {
    characterName: "Gargantuar",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Gargantuar.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Area",
    specialAbility: "Throws imps",
  },
  {
    characterName: "Jetpack Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ 2"],
    Link: "images/JetpackZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "Far Future",
    damageType: "None",
    specialAbility: "Bypasses plants",
  },
  {
    characterName: "Balloon Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ 2"],
    Link: "images/BalloonZombie.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "None",
    specialAbility: "Floats over plants",
  },
  {
    characterName: "Fume-shroom",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Fume-shroom.png",
    plantType: "Fungal",
    sunCost: "75",
    world: "Dark Ages",
    damageType: "Piercing",
    specialAbility: "Pierces through shields",
  },
  {
    characterName: "Power Lily",
    characterType: "Plant",
    gameVersions: ["PvZ"],
    Link: "images/PowerLily.png",
    plantType: "Support",
    sunCost: "150",
    world: "None",
    damageType: "None",
    specialAbility: "Produces Plant Food",
  },
  {
    characterName: "Zomboss",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Zomboss.png",
    plantType: "None",
    sunCost: "None",
    world: "None",
    damageType: "Area",
    specialAbility: "Controls boss vehicles",
  },
  {
    characterName: "Garlic",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Link: "images/Garlic.png",
    plantType: "Defensive",
    sunCost: "50",
    world: "None",
    damageType: "None",
    specialAbility: "Redirects zombies",
  },
];

export { characters };
