let characters = [
  {
    characterName: "Peashooter",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: ["Winter Peashooter", "Repeater", "Threepeater"],
  },
  {
    characterName: "Sunflower",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: ["Twin Sunflower", "Sunflower (PvZ 2)"],
  },
  {
    characterName: "Wall-nut",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: ["Tall-nut", "Winter Wall-nut"],
  },
  {
    characterName: "Cherry Bomb",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: ["Jalapeno", "Explode-o-nut"],
  },
  {
    characterName: "Snow Pea",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: ["Iceberg Lettuce"],
  },
  {
    characterName: "Pea Pod",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: ["Scaredy-shroom"],
  },
  {
    characterName: "Torchwood",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Grave Buster",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Magnolia",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Repeater",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Cabbage-pult",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Kernel-pult",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Tangle Kelp",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Snapdragon",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Jalapeno",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Mistletoe",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Pineapple",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Chili Bean",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Aloe",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Bonk Choy",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Pea Pod",
    characterType: "Plant",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Lily Pad",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Squash",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Hypno-shroom",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: ["Digger Zombie", "Zomboni", "Buckethead Zombie"],
  },
  {
    characterName: "Conehead Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Football Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Digger Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Zomboni",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Buckethead Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Squeaky Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Disco Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Gargantuar",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Jetpack Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Balloon Zombie",
    characterType: "Zombie",
    gameVersion: "PvZ 2",
    Variants: [""],
  },
  {
    characterName: "Grim Reaper",
    characterType: "Zombie",
    gameVersion: "PvZ",z
    Variants: [""],
  },
  {
    characterName: "Fume-shroom",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Power Lily",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Zomboss",
    characterType: "Zombie",
    gameVersion: "PvZ",
    Variants: [""],
  },
  {
    characterName: "Garlic",
    characterType: "Plant",
    gameVersion: "PvZ",
    Variants: [''],
  }
];
