let characters = [
  {
    characterName: "Peashooter",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Peashooter",
    Link: "images/Peashooter.png",
  },
  {
    characterName: "Snow Pea",
    characterType: "Plant",
    gameVersions: ["PvZ"],
    Original: "Peashooter",
    Link: "images/SnowPea.png",
  },
  {
    characterName: "Sunflower",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Sunflower",
    Link: "images/Sunflower.png",
  },
  {
    characterName: "Wall-nut",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Wall-nut",
    Link: "images/Wall-nut.png",
  },
  {
    characterName: "Cherry Bomb",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Cherry Bomb",
    Link: "images/CherryBomb.png",
  },
  {
    characterName: "Pea Pod",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Pea Pod",
    Link: "images/PeaPod.png",
  },
  {
    characterName: "Torchwood",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Torchwood",
    Link: "images/Torchwood.png",
  },
  {
    characterName: "Grave Buster",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Grave Buster",
    Link: "images/GraveBuster.png",
  },
  {
    characterName: "Steel-Magnolia",
    characterType: "Plant",
    gameVersions: ["PvZ Heros"],
    Original: "Steel-Magnolia",
    Link: "images/Steel-Magnolia.png",
  },
  {
    characterName: "Cabbage-pult",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Cabbage-pult",
    Link: "images/Cabbage-pult.png",
  },
  {
    characterName: "Kernel-pult",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Kernel-pult",
    Link: "images/Kernel-pult.png",
  },
  {
    characterName: "Tangle Kelp",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Tangle Kelp",
    Link: "images/TangleKelp.png",
  },
  {
    characterName: "Snapdragon",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Snapdragon",
    Link: "images/Snapdragon.png",
  },
  {
    characterName: "Jalapeno",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Jalapeno",
    Link: "images/Jalapeno.png",
  },
  {
    characterName: "Mistletoe",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Mistletoe",
    Link: "images/Mistletoe.png",
  },
  {
    characterName: "Pineapple",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Pineapple",
    Link: "images/Pineapple.png",
  },
  {
    characterName: "Chili Bean",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Chili Bean",
    Link: "images/ChiliBean.png",
  },
  {
    characterName: "Aloe",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Aloe",
    Link: "images/Aloe.png",
  },
  {
    characterName: "Bonk Choy",
    characterType: "Plant",
    gameVersions: ["PvZ 2"],
    Original: "Bonk Choy",
    Link: "images/BonkChoy.png",
  },
  {
    characterName: "Lily Pad",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Lily Pad",
    Link: "images/LilyPad.png",
  },
  {
    characterName: "Squash",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Squash",
    Link: "images/Squash.png",
  },
  {
    characterName: "Hypno-shroom",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Hypno-shroom",
    Link: "images/Hypno-shroom.png",
  },
  {
    characterName: "Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Zombie",
    Link: "images/Zombie.png",
  },
  {
    characterName: "Conehead Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Conehead Zombie",
    Link: "images/ConeheadZombie.png",
  },
  {
    characterName: "Football Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Football Zombie",
    Link: "images/FootballZombie.png",
  },
  {
    characterName: "Digger Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Digger Zombie",
    Link: "images/DiggerZombie.png",
  },
  {
    characterName: "Zomboni",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Zomboni",
    Link: "images/Zomboni.png",
  },
  {
    characterName: "Buckethead Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Buckethead Zombie",
    Link: "images/BucketheadZombie.png",
  },
  {
    characterName: "Disco Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Disco Zombie",
    Link: "images/DiscoZombie.png",
  },
  {
    characterName: "Gargantuar",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Gargantuar",
    Link: "images/Gargantuar.png",
  },
  {
    characterName: "Jetpack Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ 2"],
    Original: "Jetpack Zombie",
    Link: "images/JetpackZombie.png",
  },
  {
    characterName: "Balloon Zombie",
    characterType: "Zombie",
    gameVersions: ["PvZ 2"],
    Original: "Balloon Zombie",
    Link: "images/BalloonZombie.png",
  },
  {
    characterName: "Fume-shroom",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Fume-shroom",
    Link: "images/Fume-shroom.png",
  },
  {
    characterName: "Power Lily",
    characterType: "Plant",
    gameVersions: ["PvZ"],
    Original: "Power Lily",
    Link: "images/PowerLily.png",
  },
  {
    characterName: "Zomboss",
    characterType: "Zombie",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Zomboss",
    Link: "images/Zomboss.png",
  },
  {
    characterName: "Garlic",
    characterType: "Plant",
    gameVersions: ["PvZ", "PvZ 2"],
    Original: "Garlic",
    Link: "images/Garlic.png",
  },
];
